Feature/edt
ungdev/etuutt-api pull request #25
Opened 2021-12-05 23:05 UTC by nicholsp2

## Description

Added a new entry point for "user" to retrieve said user's schedule through a new controller.
Only the courses of the current semester are exposed.

There might be code on the UE entity coming from another branch that was improperly cleaned.

## Checklist

### Implementation

* [x] Files and variables have a name explaining what they do.
* [ ] Updating the DB schemas and seeding the tables do not generates errors.
* [x] All code repeted more than 2 times has been refactored in a dedicated file or function.
* [x] Debugs have been removed : `dd()` | `dump()`

### Tools

* [x] PHP CS Fixer has fixed all files inside the `src` folder.
* [x] All commits have been done using Commitizen.

### Documentation

* [x] All new classes and non-trivial functions have a code documentation.
* [x] There are comments to explain complex parts inside your code.
* [x] If a new folder is created, it has been added and explained inside the "Folder structure" part of the `README.md` file.

2021-12-19 09:05 UTC, ThomasRitaine commented on src/Controller/GetEDTController.php
> +        $now = new DateTime('now');
Le constructeur appelé sans paramètre crée un objet DateTime avec le timestamp actuel

2021-12-19 09:07 UTC, ThomasRitaine commented on src/Controller/GetEDTController.php
> +        $currentSemesterCode = $repository->getSemesterOfDate($now)->getCode();
Puisque tu ne réutilises pas ta variable `$now`, je te conseille de déclarer ta date directement dans le `$repository->getSemesterOfDate()`

2021-12-19 09:14 UTC, ThomasRitaine commented on src/Controller/GetEDTController.php
> +class GetEDTController extends AbstractController
Il faudrait ajouter de la documentation de code parce que j'ai du mal à comprendre

2021-12-19 09:24 UTC, ThomasRitaine commented on src/Entity/User.php
> +        return $tmp;*/
Dead code à enlever

2021-12-19 09:26 UTC, ThomasRitaine commented on src/Entity/User.php
> +                    'groups' => ['user:read:one:edt'],
Que penses-tu de changer le code du groupe en `user-edt:read:one` pour garder la convention `entité+spécification:action:complément` ?

2021-12-19 13:33 UTC, ThomasRitaine requested changes
Super travail Pierre 😉
Est-ce que tu peux ajouter un peu de documentation du code et faire le ménage dans ce que tu mets dans cette PR ? Tu peux toujours re-créer une autre PR avec le restes des modifs que tu veux apporter 👍

2022-01-02 14:52 UTC, ThomasRitaine requested changes

2022-01-02 14:52 UTC, ThomasRitaine commented on src/Controller/GetEDTController.php
> +use Symfony\Bundle\FrameworkBundle\Controller\AbstractController; //needed to be used from platform API configuration (see User.php)
Ces composants sont déjà très bien documentés par Symfony, pas besoin d'ajouter d'explication ici 😉

2022-01-02 14:52 UTC, ThomasRitaine commented on src/Controller/GetEDTController.php
> +class GetEDTController extends AbstractController
Je parlais d'ajouter de la documentation sur la classe. A quoi sert-elle, qui l'appelle ?
Voici un exemple de documentation sur un controller
https://github.com/ungdev/etuutt-api/blob/ad786de1dd5f6bce0d7267fff11b2c9e40f693ba/src/Controller/SoftDeleteController.php#L12-L15

2022-01-02 14:52 UTC, ThomasRitaine commented on src/Repository/SemesterRepository.php
> +    public function getSemesterOfDate()
La méthode `getSemesterOfDate()` est censée retourner le semestre dans lequel est inclue la date donnée en paramètre, comme indiqué dans la documentation de la méthode. Pourquoi retirer ce paramètre ?

Si tu veux que lorsque cette méthode est appelée sans argument, la date choisie soit celle d'ajourd'hui, alors tu peux le faire avec PHP sans passer par les fonctions PHP `func_num_args()` et `func_get_args($int)`.
Voici comment faire :
`public function getSemesterOfDate(DateTimeInterface $date = new DateTime())`

2023-01-25 01:34 UTC, TeddyRoncin approved these changes

2023-01-26 14:31 UTC, merged